button_option: stbc_large
comments: 0
late_load: 0
location: block
node_types:
  article: article
  page: page
  homepage: null
  lamp: null
option_extras:
  'Google Plus One:plusone': '0'
  'Facebook Like:fblike': '0'
option_neworzero: 0
option_onhover: 1
option_shorten: 1
service_option: '''ShareThis:sharethis'''
twitter_handle: ''
twitter_recommends: ''
twitter_suffix: ''
webform_options: ''
weight: 10
widget_option: st_multi
cns:
  donotcopy: null
  hashaddress: null
sharethisnodes:
  article:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
  page:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
  homepage:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
  lamp:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
_core:
  default_config_hash: OUePCWmQ_tUOCD4VF7-AP0maPJi2Y18f0JvNTgThhRQ
publisherID: dr-4bae2c4e-59cb-16ac-27f-72313812c61a
callesi: '0'
