print: 'Site is still under development! Please visit us soon again ;)'
allow_cli: true
_core:
  default_config_hash: NfapC3dpo1sgPOpAyD-rqMkL3OzOfjJyi8FIK0GWpW8
credential_provider: shield
credentials:
  shield:
    user: web
    pass: goteam
